/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	gatewayapiapisxv1alpha1 "sigs.k8s.io/gateway-api/apisx/v1alpha1"
	versioned "sigs.k8s.io/gateway-api/pkg/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/gateway-api/pkg/client/informers/externalversions/internalinterfaces"
	apisxv1alpha1 "sigs.k8s.io/gateway-api/pkg/client/listers/apisx/v1alpha1"
)

// XMeshInformer provides access to a shared informer and lister for
// XMeshes. Prefer using the type-safe variant (see [TypedXMeshInformer]).
type XMeshInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apisxv1alpha1.XMeshLister
}

// TypedXMeshInformer provides access to a shared informer and lister for
// XMeshes, including the type-safe TypedInformer variant.
// It is a superset of XMeshInformer.
type TypedXMeshInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() XMeshIndexInformer
	Lister() apisxv1alpha1.XMeshLister
}

// XMeshIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type XMeshIndexInformer cache.TypedSharedIndexInformer[*gatewayapiapisxv1alpha1.XMesh]

// XMeshHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for XMesh.
type XMeshHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*gatewayapiapisxv1alpha1.XMesh]

// XMeshDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for XMesh.
type XMeshDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*gatewayapiapisxv1alpha1.XMesh]

// XMeshFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for XMesh.
type XMeshFilteringHandler = cache.TypedFilteringResourceEventHandler[*gatewayapiapisxv1alpha1.XMesh]

// XMeshIndexers is a specialization of [cache.TypedIndexers] for XMesh.
type XMeshIndexers = cache.TypedIndexers[*gatewayapiapisxv1alpha1.XMesh]

// DeletedXMesh is a specialization of [cache.DeletedObject] for XMesh.
type DeletedXMesh = cache.DeletedObject[*gatewayapiapisxv1alpha1.XMesh]

type xMeshInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewXMeshInformer constructs a new informer for XMesh type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedXMeshInformer]).
func NewXMeshInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewXMeshInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedXMeshInformer constructs a new informer for XMesh type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedXMeshInformer(client versioned.Interface, resyncPeriod time.Duration, indexers XMeshIndexers) XMeshIndexInformer {
	return NewTypedXMeshInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredXMeshInformer constructs a new informer for XMesh type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredXMeshInformer]).
func NewFilteredXMeshInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedXMeshInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredXMeshInformer constructs a new informer for XMesh type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredXMeshInformer(client versioned.Interface, resyncPeriod time.Duration, indexers XMeshIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) XMeshIndexInformer {
	return NewTypedXMeshInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewXMeshInformerWithOptions constructs a new informer for XMesh type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedXMeshInformerWithOptions]).
func NewXMeshInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedXMeshInformerWithOptions(client, options)
}

// NewTypedXMeshInformerWithOptions constructs a new informer for XMesh type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedXMeshInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) XMeshIndexInformer {
	gvr := schema.GroupVersionResource{Group: "gateway.networking.x-k8s.io", Version: "v1alpha1", Resource: "xmeshs"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*gatewayapiapisxv1alpha1.XMesh](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ExperimentalV1alpha1().XMeshes().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ExperimentalV1alpha1().XMeshes().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ExperimentalV1alpha1().XMeshes().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ExperimentalV1alpha1().XMeshes().Watch(ctx, opts)
			},
		}, client),
		&gatewayapiapisxv1alpha1.XMesh{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *xMeshInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedXMeshInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *xMeshInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *xMeshInformer) TypedInformer() XMeshIndexInformer {
	return cache.NewTypedSharedIndexInformer[*gatewayapiapisxv1alpha1.XMesh](f.factory.InformerFor(&gatewayapiapisxv1alpha1.XMesh{}, f.defaultInformer))
}

func (f *xMeshInformer) Lister() apisxv1alpha1.XMeshLister {
	return apisxv1alpha1.NewXMeshLister(f.Informer().GetIndexer())
}

// ToTypedXMeshInformer converts an untyped informer into a TypedXMeshInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *XMesh. If that is not the case, calling type-safe methods of the returned
// TypedXMeshInformer leads to runtime panics. A safer alternative is to pass
// around a TypedXMeshInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedXMeshInformer(informer XMeshInformer) TypedXMeshInformer {
	if informer, ok := informer.(TypedXMeshInformer); ok {
		return informer
	}
	return &xMeshTypedInformerAdapter{informer}
}

type xMeshTypedInformerAdapter struct {
	XMeshInformer
}

func (a *xMeshTypedInformerAdapter) TypedInformer() XMeshIndexInformer {
	return cache.NewTypedSharedIndexInformer[*gatewayapiapisxv1alpha1.XMesh](a.Informer())
}

// ToXMeshIndexInformer converts an untyped informer into a XMeshIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *XMesh. If that is not the case, calling type-safe methods of the returned
// XMeshIndexInformer leads to runtime panics. A safer alternative is to pass
// around a XMeshIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToXMeshIndexInformer(informer cache.SharedIndexInformer) XMeshIndexInformer {
	if informer, ok := informer.(XMeshIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*gatewayapiapisxv1alpha1.XMesh](informer)
}
